SET DATEFORMAT dmy

DROP TABLE Team_Pilot
DROP TABLE Engine
DROP TABLE Team
DROP TABLE Result
DROP TABLE Pilot
DROP TABLE Season_GrandPrix
DROP TABLE Season
DROP TABLE System
DROP TABLE Pilot_Status
DROP TABLE Team_Status
DROP TABLE GrandPrix
DROP TABLE Autodrom
DROP TABLE Country

CREATE TABLE Team (
	Team_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	Name VARCHAR(100) NOT NULL UNIQUE
	);

CREATE TABLE Team_Pilot (
    Team_Pilot_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(201,1),
	Pilot_ID SMALLINT NOT NULL,
	Team_ID SMALLINT NOT NULL,
	Season_GrandPrix_ID SMALLINT NOT NULL
	);

CREATE TABLE Pilot (
	Pilot_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(301,1),
	First_Name VARCHAR(100) NOT NULL,
	Last_Name VARCHAR(100) NOT NULL,
	Country_ID SMALLINT NOT NULL	
	);

CREATE TABLE Engine (
	Engine_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(401,1),
	Team_ID SMALLINT NOT NULL,
	Season_GrandPrix_ID SMALLINT NOT NULL,
	Name VARCHAR(100) NOT NULL
	);

CREATE TABLE GrandPrix (
	GrandPrix_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(501,1),
	Name VARCHAR(100) NOT NULL UNIQUE
	);

CREATE TABLE Season_GrandPrix (
	Season_GrandPrix_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(701,1),
	Season_ID SMALLINT NOT NULL,
	GrandPrix_ID SMALLINT NOT NULL,
	Date DATETIME NOT NULL,
	Attendance INTEGER,
	Laps INTEGER NOT NULL,
	Lap_Length INTEGER NOT NULL,
	Autodrom_ID SMALLINT NOT NULL
	);

CREATE TABLE Country (
	Country_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(901,1),
	Name VARCHAR(100) UNIQUE
	);

CREATE TABLE Autodrom (
	Autodrom_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(801,1),
	Name VARCHAR(100) UNIQUE,
	Country_ID SMALLINT NOT NULL
	);

CREATE TABLE Result (
    Result_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(1001,1),
	Season_GrandPrix_ID SMALLINT NOT NULL,
	Pilot_ID SMALLINT NOT NULL,
	Position SMALLINT NOT NULL,
	Laps INTEGER,
	Time VARCHAR(100) NOT NULL,
	Pitstops INTEGER,
	Start_Position INTEGER,
	Average_Speed NUMERIC (6,3),
	Pilot_Status_ID SMALLINT NOT NULL DEFAULT(2501),
	Team_Status_ID SMALLINT NOT NULL DEFAULT(2601)
	);

CREATE TABLE Pilot_Status (
	Pilot_Status_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(2501,1),
	Description VARCHAR(100) NOT NULL UNIQUE
	);

CREATE TABLE Team_Status (
	Team_Status_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(2601,1),
	Description VARCHAR(100) NOT NULL UNIQUE
	);

CREATE TABLE Season (
	Season_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(601,1),
	Description VARCHAR(100) NOT NULL UNIQUE,
	System_ID SMALLINT NOT NULL DEFAULT (2401)
	);

CREATE TABLE System (
	System_ID SMALLINT NOT NULL PRIMARY KEY IDENTITY(2401,1),
	Description VARCHAR(100) NOT NULL UNIQUE	
	);

ALTER TABLE Team_Pilot ADD
	FOREIGN KEY (Team_ID)
	REFERENCES Team (Team_ID),
	FOREIGN KEY (Pilot_ID)
	REFERENCES Pilot (Pilot_ID),
	FOREIGN KEY (Season_GrandPrix_ID)
	REFERENCES Season_GrandPrix (Season_GrandPrix_ID)

ALTER TABLE Pilot ADD
	FOREIGN KEY (Country_ID)
	REFERENCES Country (Country_ID)

ALTER TABLE Autodrom ADD
	FOREIGN KEY (Country_ID)
	REFERENCES Country (Country_ID)

ALTER TABLE Engine ADD
	FOREIGN KEY (Team_ID)
	REFERENCES Team (Team_ID),
	FOREIGN KEY (Season_GrandPrix_ID)
	REFERENCES Season_GrandPrix (Season_GrandPrix_ID)

ALTER TABLE Season_GrandPrix ADD
	FOREIGN KEY (GrandPrix_ID)
	REFERENCES GrandPrix (GrandPrix_ID),
	FOREIGN KEY (Autodrom_ID)
	REFERENCES Autodrom (Autodrom_ID),
	FOREIGN KEY (Season_ID)
	REFERENCES Season (Season_ID)

ALTER TABLE Result ADD
	FOREIGN KEY (Pilot_Status_ID)
	REFERENCES Pilot_Status (Pilot_Status_ID),
	FOREIGN KEY (Team_Status_ID)
	REFERENCES Team_Status (Team_Status_ID),
	FOREIGN KEY (Season_GrandPrix_ID)
	REFERENCES Season_GrandPrix (Season_GrandPrix_ID),
	FOREIGN KEY (Pilot_ID)
	REFERENCES Pilot (Pilot_ID)

ALTER TABLE Season ADD
	FOREIGN KEY (System_ID)
	REFERENCES System (System_ID)	

	